
name: Updates

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Get lastest eyes_selenium verison
        run: VERSION=$(gem search -e eyes_selenium | grep eyes_selenium | grep -E -o "\d+.\d+.\d+")

      - name: Update gemfile and install dependencies
        run: bundle remove eyes_selenium && bundle add eyes_selenium -v $VERSION

      - name: Install dependencies
        run: bundle install

      - name: Run test
        run: bundle exec ruby simple_test_script.rb
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master'